# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tedp < Formula
  desc "Tedplatform CLI — deploy apps to managed Kubernetes"
  homepage "https://tederga.org"
  version "0.55.48"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.48/tedp_0.55.48_macOS_x86_64.tar.gz"
      sha256 "459647134662c29109828d2ff240b77f8171c423c0e0cc9840beb3661ea26875"

      define_method(:install) do
        bin.install "tedp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.48/tedp_0.55.48_macOS_arm64.tar.gz"
      sha256 "6701897624939504cbf0085f006de33198fb478a6305100ad19c12f5f7b57c5f"

      define_method(:install) do
        bin.install "tedp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.48/tedp_0.55.48_Linux_x86_64.tar.gz"
      sha256 "a2d260a806ee5f2c039e2ddb9236a19defe99e8b16d88756414371c99761980f"
      define_method(:install) do
        bin.install "tedp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.48/tedp_0.55.48_Linux_arm64.tar.gz"
      sha256 "1b26a9890442d91e95f05abed31216cb644aa2db4f63fb61d3235f54e4095d71"
      define_method(:install) do
        bin.install "tedp"
      end
    end
  end

  test do
    system "#{bin}/tedp", "version"
  end
end
