# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tedp < Formula
  desc "Tedplatform CLI — deploy apps to managed Kubernetes"
  homepage "https://tederga.org"
  version "0.55.49"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.49/tedp_0.55.49_macOS_x86_64.tar.gz"
      sha256 "9e941ca6f58144b4e1f53927ae67654faeaa726cc9c3d505980622c86736d587"

      define_method(:install) do
        bin.install "tedp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.49/tedp_0.55.49_macOS_arm64.tar.gz"
      sha256 "023dd8b0abdc227c4f2c0bb107805604099a1b2adbb9221ece23db3d9d3a98fb"

      define_method(:install) do
        bin.install "tedp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.49/tedp_0.55.49_Linux_x86_64.tar.gz"
      sha256 "8df9c2351667684a33a31854999644f42a12370355e46ee2ec958d4e2eb7b347"
      define_method(:install) do
        bin.install "tedp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TedergaGO/homebrew-tap/releases/download/v0.55.49/tedp_0.55.49_Linux_arm64.tar.gz"
      sha256 "38ee1565faf092f88e912b0acc3792d140b0f2c85c107fbf0ab2d5ba8e33f147"
      define_method(:install) do
        bin.install "tedp"
      end
    end
  end

  test do
    system "#{bin}/tedp", "version"
  end
end
